In [2]:
import numpy as np 

my_list = [1,2,3,4]

my_list = my_list * 2 

print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [3]:
array = np.array([1,2,3,4])

array = array * 2 

print(array)


[2 4 6 8]


---

1-D array

In [11]:
arr = np.array([1,2,3,4])

In [12]:
arr

array([1, 2, 3, 4])

---

2-D array

In [14]:
arr2 = np.array([[1,2,3],
                [4,5,6]])

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

---

np.zero()

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

np.zeros() -> 2D

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

----

np.ones() 

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.eye()

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])