1. reshape() : Used to change the structure of an array.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

In [2]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

2. flatten()

Converts multidimensional array into 1D array.

In [6]:
arr = np.array([[1,2,3], [4,5,6]])

arr.flatten()

array([1, 2, 3, 4, 5, 6])

3. ravel()

Also converts to 1D.

In [8]:
print(arr.ravel())

[1 2 3 4 5 6]
