1. np.stack()

- General stacking function.

- It joins arrays along a new axis.

In [1]:
import numpy as np 

a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
result = np.stack((a,b))

In [4]:
result

array([[1, 2, 3],
       [4, 5, 6]])

Axis

-  Default:

axis=0

Meaning:
stack row-wise.

axis=1

Meaning : coloumns wise joining


In [8]:
np.stack((a,b) , axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [10]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
a = np.array([1,2])
b = np.array([3,4])

np.stack((a,b)) 

array([[1, 2],
       [3, 4]])

In [12]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])